name: serverless deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master branch
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: donwload ffmpeg
        run: ./setffmpeg.sh

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

      - name: Install NPM dependencies
        run: npm install

      - name: Deploy
        run: sls deploy
